/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.currencyconverter.Enum;

/**
 *
 * @author Usuario
 */
public enum Country {
    FIJI("Fiyi", "FJD"),
    MEXICO("México", "MXN"),
    SEYCHELLES("Seychelles", "SCR"),
    TUVALU("Tuvalu", "TVD"),
    CONGO("República Democrática del Congo", "CDF"),
    BARBADOS("Barbados", "BBD"),
    GUATEMALA("Guatemala", "GTQ"),
    CHILE("Chile", "CLP"),
    HONDURAS("Honduras", "HNL"),
    UGANDA("Uganda", "UGX"),
    SUDAFRICA("Sudáfrica", "ZAR"),
    TUNEZ("Túnez", "TND"),
    SANTO_TOME_PRINCIPE("Santo Tomé y Príncipe", "STN"),
    BAHAMAS("Bahamas", "BSD"),
    SUDAN("Sudán", "SDG"),
    IRAK("Irak", "IQD"),
    CUBA("Cuba", "CUP"),
    GAMBIA("Gambia", "GMD"),
    TAIWAN("Taiwán", "TWD"),
    SERBIA("Serbia", "RSD"),
    REPUBLICA_DOMINICANA("República Dominicana", "DOP"),
    COMORAS("Comoras", "KMF"),
    MALASIA("Malasia", "MYR"),
    ISLAS_MALVINAS("Islas Malvinas", "FKP"),
    AFRICA_OCCIDENTAL("África Occidental Franco CFA", "XOF"),
    GEORGIA("Georgia", "GEL"),
    URUGUAY("Uruguay", "UYU"),
    MARRUECOS("Marruecos", "MAD"),
    CABO_VERDE("Cabo Verde", "CVE"),
    TONGA("Tonga", "TOP"),
    AZERBAIYAN("Azerbaiyán", "AZN"),
    OMAN("Omán", "OMR"),
    PAPUA_NUEVA_GUINEA("Papúa Nueva Guinea", "PGK"),
    KENIA("Kenia", "KES"),
    SUECIA("Suecia", "SEK"),
    BUTAN("Bután", "BTN"),
    UCRANIA("Ucrania", "UAH"),
    GUINEA_ECUATORIAL("Guinea Ecuatorial", "XAF"),
    ERITREA("Eritrea", "ERN"),
    MOZAMBIQUE("Mozambique", "MZN"),
    ARGENTINA("Argentina", "ARS"),
    CATAR("Catar", "QAR"),
    IRAN("Irán", "IRR"),
    CHINA("China", "CNY"),
    TAILANDIA("Tailandia", "THB"),
    UZBEKISTAN("Uzbekistán", "UZS"),
    FRANCO_CFP("Franco CFP", "XPF"),
    BANGLADESH("Bangladesh", "BDT"),
    LIBIA("Libia", "LYD"),
    BERMUDAS("Bermudas", "BMD"),
    KUWAIT("Kuwait", "KWD"),
    FILIPINAS("Filipinas", "PHP"),
    RUSIA("Rusia", "RUB"),
    PARAGUAY("Paraguay", "PYG"),
    ISLANDIA("Islandia", "ISK"),
    JAMAICA("Jamaica", "JMD"),
    COLOMBIA("Colombia", "COP"),
    ESTADOS_UNIDOS("Estados Unidos", "USD"),
    MACEDONIA_DEL_NORTE("Macedonia del Norte", "MKD"),
    ARGELIA("Argelia", "DZD"),
    PANAMA("Panamá", "PAB"),
    GUERNSEY("Guernsey", "GGP"),
    SINGAPUR("Singapur", "SGD"),
    ETIOPIA("Etiopía", "ETB"),
    JERSEY("Jersey", "JEP"),
    KIRGUISTAN("Kirguistán", "KGS"),
    SOMALIA("Somalia", "SOS"),
    VANUATU("Vanuatu", "VUV"),
    LAOS("Laos", "LAK"),
    BRUNEI("Brunéi", "BND"),
    AFRICA_CENTRAL_FRANCO_CFA("África Central Franco CFA", "XAF"),
    LIBERIA("Liberia", "LRD"),
    SUIZA("Suiza", "CHF"),
    CROACIA("Croacia", "HRK"),
    ALBANIA("Albania", "ALL"),
    YIBUTI("Yibuti", "DJF"),
    VENEZUELA("Venezuela", "VES"),
    ZAMBIA("Zambia", "ZMW"),
    TANZANIA("Tanzania", "TZS"),
    VIETNAM("Vietnam", "VND"),
    AUSTRALIA("Australia", "AUD"),
    ISRAEL("Israel", "ILS"),
    GHANA("Ghana", "GHS"),
    GUYANA("Guyana", "GYD"),
    BOLIVIA("Bolivia", "BOB"),
    CAMBOYA("Camboya", "KHR"),
    MOLDAVIA("Moldavia", "MDL"),
    INDONESIA("Indonesia", "IDR"),
    ISLAS_CAIMAN("Islas Caimán", "KYD"),
    ARMENIA("Armenia", "AMD"),
    BOTSUANA("Botsuana", "BWP"),
    SANTA_ELENA("Santa Elena, Ascensión y Tristán de Acuña", "SHP"),
    TURQUIA("Turquía", "TRY"),
    LIBANO("Líbano", "LBP"),
    TAYIKISTAN("Tayikistán", "TJS"),
    JORDANIA("Jordania", "JOD"),
    EMIRATOS_ARABES_UNIDOS("Emiratos Árabes Unidos", "AED"),
    HONG_KONG("Hong Kong", "HKD"),
    RUANDA("Ruanda", "RWF"),
    EURO("Euro", "EUR"),
    LESOTO("Lesoto", "LSL"),
    DINAMARCA("Dinamarca", "DKK"),
    CANADA("Canadá", "CAD"),
    ISLASCOCOS("Islas Cocos", "AUD"),
    BULGARIA("Bulgaria", "BGN"),
    MYANMAR("Myanmar", "MMK"),
    MAURICIO("Mauricio", "MUR"),
    NORUEGA("Noruega", "NOK"),
    SIRIA("Siria", "SYP"),
    REINO_UNIDO("Reino Unido", "GBP"),
    ZIMBABUE("Zimbabue", "ZWL"),
    GIBRALTAR("Gibraltar", "GIP"),
    RUMANIA("Rumania", "RON"),
    SRI_LANKA("Sri Lanka", "LKR"),
    NIGERIA("Nigeria", "NGN"),
    COSTA_RICA("Costa Rica", "CRC"),
    REPUBLICA_CHECA("República Checa", "CZK"),
    PAKISTAN("Pakistán", "PKR"),
    DOLAR_CARIBE_ORIENTAL("Dólar del Caribe Oriental", "XCD"),
    ANTILLAS_NEERLANDESAS("Antillas Neerlandesas", "ANG"),
    HAITI("Haití", "HTG"),
    BAHRAIN("Baréin", "BHD"),
    KAZAJISTAN("Kazajistán", "KZT"),
    SURINAM("Surinam", "SRD"),
    SUAZILANDIA("Suazilandia", "SZL"),
    ARABIA_SAUDITA("Arabia Saudita", "SAR"),
    TRINIDAD_Y_TOBAGO("Trinidad y Tobago", "TTD"),
    YEMEN("Yemen", "YER"),
    MALDIVAS("Maldivas", "MVR"),
    AFGANISTAN("Afganistán", "AFN"),
    INDIA("India", "INR"),
    ARUBA("Aruba", "AWG"),
    COREA_DEL_SUR("Corea del Sur", "KRW"),
    NEPAL("Nepal", "NPR"),
    JAPON("Japón", "JPY"),
    MONGOLIA("Mongolia", "MNT"),
    ANGOLA("Angola", "AOA"),
    POLONIA("Polonia", "PLN"),
    ISLAS_SALOMON("Islas Salomón", "SBD"),
    BIELORRUSIA("Bielorrusia", "BYN"),
    HUNGRIA("Hungría", "HUF"),
    BURUNDI("Burundi", "BIF"),
    MALAUI("Malaui", "MWK"),
    MADAGASCAR("Madagascar", "MGA"),
    DERECHOS_ESPECIALES_DE_GIRO("Derechos Especiales de Giro", "XDR"),
    BELICE("Belice", "BZD"),
    BOSNIA_Y_HERZEGOVINA("Bosnia y Herzegovina", "BAM"),
    EGIPTO("Egipto", "EGP"),
    MACAO("Macao", "MOP"),
    NAMIBIA("Namibia", "NAD"),
    SUDAN_DEL_SUR("Sudán del Sur", "SSP"),
    NICARAGUA("Nicaragua", "NIO"),
    PERU("Perú", "PEN"),
    NUEVA_ZELANDA("Nueva Zelanda", "NZD"),
    SAMOA("Samoa", "WST"),
    TURKMENISTAN("Turkmenistán", "TMT"),
    BRASIL("Brasil", "BRL"),
    SIERRA_LEONA("Sierra Leona","SLE"),
    GUNIEA("Guine", "GNF"),
    MAURITANIA("Mauritania", "MRU"),
    ISLAS_FEROE("Islas Feroe", "FOK"),
    ISLA_DE_MAN("Isla de Man", "KID"),
    ISLAS_DEL_HOMBRE("Isla del hombre", "IMP");
    
    
    private final String countryName;
    private final String currencyCode;
    
    Country(String countryName, String currencyCode) {
        this.countryName = countryName;
        this.currencyCode = currencyCode;
    }

    public String getCountryName() {
        return countryName;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

}
